#!/bin/bash
# ---------------------------------------------------------------------------
# docs/cf-build.sh
#
# Purpose:
#   Generate `docs/_updated.json` — a map of { filepath: ISO-8601 commit time }
#   for every file under docs/, so Docsify can display an accurate
#   "Last Modified" date on every page.
#
# How paths work here:
#   - This script lives in `docs/` and is run with `docs/` as CWD.
#   - `git ls-files .` therefore lists only files under docs/, with paths
#     relative to docs/ (e.g. "README.md", "guide/setup.md").
#   - Those keys match Docsify's `vm.route.file` exactly when the site is
#     served with docs/ as its root.
#
# IMPORTANT:
#   Do NOT use `git fetch --unshallow` here. Cloudflare Pages uses a shallow
#   clone AND restricts outbound network access, so `git fetch` is unreliable.
#   The authoritative `_updated.json` is generated by GitHub Actions
#   (.github/workflows/update-times.yml), which uses `fetch-depth: 0`.
#   This script only acts as a fallback when the JSON is missing.
#
# Cloudflare Pages config:
#   Root directory          : docs
#   Build command           : chmod +x cf-build.sh && ./cf-build.sh
#   Build output directory  : /
# ---------------------------------------------------------------------------

set -e

# Ensure we're in the directory containing this script (docs/)
cd "$(dirname "$0")"

if [ -f _updated.json ]; then
  echo "cf-build.sh: _updated.json already present, skipping generation."
  exit 0
fi

echo "cf-build.sh: _updated.json missing, generating (fallback mode)."

python3 - <<'PYEOF'
import subprocess, json, os

# List only files under the current directory (docs/), relative to docs/.
result = subprocess.run(['git', 'ls-files', '.'],
                        capture_output=True, text=True, check=True)
files = [f for f in result.stdout.splitlines() if f]

data = {}
for f in files:
    if not os.path.isfile(f):
        continue
    # %cI = committer date in strict ISO-8601 format
    r = subprocess.run(['git', 'log', '-1', '--format=%cI', '--', f],
                       capture_output=True, text=True)
    ts = r.stdout.strip()
    if ts:
        data[f] = ts

with open('_updated.json', 'w', encoding='utf-8') as fp:
    json.dump(data, fp, ensure_ascii=False, indent=2)

print(f"cf-build.sh: wrote docs/_updated.json with {len(data)} entries.")
for k, v in list(data.items())[:5]:
    print(f"  {v}  {k}")
PYEOF
